### ISSUE TITLE
Using Docker to run Tutorial - Configuration for Visualisation

### ISSUE THREAD

**Issue by haloted** [inkyusa/raisimGymTutorial#2]
Hi Inkyu and Jemin,
I tried to use Docker container based on the original docker image created for the ANYmal and Lakaigo setup for this tutorial and managed to make it compile as it can run RL episodes with the following output: 

> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   np_resource = np.dtype([("resource", np.ubyte, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint8 = np.dtype([("qint8", np.int8, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint16 = np.dtype([("qint16", np.int16, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   _np_qint32 = np.dtype([("qint32", np.int32, 1)])
> /usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
>   np_resource = np.dtype([("resource", np.ubyte, 1)])
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/env/env/cartpole/rsc
> W0820 13:51:58.615869 140605381912384 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/stable_baselines-2.7.0-py3.6.egg/stable_baselines/common/tf_util.py:98: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.
> 
> W0820 13:51:58.616492 140605381912384 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/stable_baselines-2.7.0-py3.6.egg/stable_baselines/common/tf_util.py:107: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.
> 
> Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /tmp/.docker.xauth which is owned by uid 1000.)
> W0820 13:51:58.723061 140605381912384 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/archi/policies.py:112: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.
> 
> W0820 13:51:58.723516 140605381912384 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/stable_baselines-2.7.0-py3.6.egg/stable_baselines/common/input.py:25: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
> 
> W0820 13:51:58.725111 140605381912384 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/archi/policies.py:436: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.flatten instead.
> [440:440:0820/135158.750565:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /tmp/.docker.xauth which is owned by uid 1000.)
> /usr/bin/xdg-open: 851: /usr/bin/xdg-open: iceweasel: not found
> /usr/bin/xdg-open: 851: /usr/bin/xdg-open: seamonkey: not found
> /usr/bin/xdg-open: 851: /usr/bin/xdg-open: mozilla: not found
> /usr/bin/xdg-open: 851: /usr/bin/xdg-open: epiphany: not found
> /usr/bin/xdg-open: 851: /usr/bin/xdg-open: konqueror: not found
> /usr/bin/xdg-open: 851: /usr/bin/xdg-open: chromium: not found
> /usr/bin/xdg-open: 851: /usr/bin/xdg-open: chromium-browser: not found
> [469:469:0820/135158.829528:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
> /usr/bin/xdg-open: 851: /usr/bin/xdg-open: www-browser: not found
> /usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
> /usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
> /usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
> /usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
> /usr/bin/xdg-open: 851: /usr/bin/xdg-open: w3m: not found
> xdg-open: no method available for opening 'http://1ba7b926c12a:6006/'
> W0820 13:51:59.074641 140605381912384 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/stable_baselines-2.7.0-py3.6.egg/stable_baselines/a2c/utils.py:156: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.
> 
> W0820 13:51:59.295579 140605381912384 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/algo/ppo2/ppo2.py:161: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.
> 
> W0820 13:51:59.327766 140605381912384 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use tf.where in 2.0, which has the same broadcast rule as np.where
> W0820 13:51:59.677419 140605381912384 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/algo/ppo2/ppo2.py:177: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.
> 
> W0820 13:51:59.919301 140605381912384 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/algo/ppo2/ppo2.py:210: The name tf.summary.merge_all is deprecated. Please use tf.compat.v1.summary.merge_all instead.
> 
> W0820 13:51:59.921238 140605381912384 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/stable_baselines-2.7.0-py3.6.egg/stable_baselines/common/base_class.py:880: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.
> 
> [RAISIM_GYM] Visualizing in RaiSimOgre
> [2019:08:20:13:52:00 OgreVis.hpp:295] Loading RaisimOgre Resource from: /raisim_build/share/raisimOgre/cmake/../rsc
> [2019:08:20:13:52:00 OgreVis.hpp:296] Loading Ogre Configuration from: /raisim_build/share/raisimOgre/cmake/../ogre/
> Average rewards in this test episode  24.37104433774948
> -------------------------------------
> | approxkl           | 0.011057173  |
> | clipfrac           | 0.13440748   |
> | ep_len_mean        | 16.3         |
> | ep_reward_mean     | 12           |
> | explained_variance | -0.00288     |
> | fps                | 27596        |
> | nupdates           | 1            |
> | policy_entropy     | 1.3917731    |
> | policy_loss        | -0.014017224 |
> | serial_timesteps   | 400          |
> | time_elapsed       | 0.468        |
> | total_timesteps    | 40100        |
> | value_loss         | 23.976883    |
> -------------------------------------
> ^CTraceback (most recent call last):
>   File "cartpole_tutorial.py", line 61, in <module>
>     record_video=cfg['record_video']
>   File "/usr/local/lib/python3.6/dist-packages/raisim_gym-0.3.0-py3.6-linux-x86_64.egg/raisim_gym/algo/ppo2/ppo2.py", line 345, in learn
>     writer, self.num_timesteps)
>   File "/usr/local/lib/python3.6/dist-packages/stable_baselines-2.7.0-py3.6.egg/stable_baselines/a2c/utils.py", line 585, in total_episode_reward_logger
>     summary = tf.Summary(value=[tf.Summary.Value(tag="episode_reward", simple_value=rew_acc[env_idx])])
>   File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation_wrapper.py", line 107, in __getattr__
>     if (self._dw_warning_count < _PER_MODULE_WARNING_LIMIT and
> KeyboardInterrupt 
By using the original docker file, I have to create new directory for the cartpole tutorial as well as moving the cartpole tutorial folder into the raisim_gym -> env -> env directories in order to make it compile. 
I encountered two problems: 
1. I was not able to visualise in Ogre as the raisimOgre window did not appear on the host computer. 
2. The tensorboard also did not appear as there was no browser installed. So I installed firefox within the image. Initially it was able to trigger a firefox pop up in the host computer however it was not able to communicate and the webpage was broken. And now I am getting the error on cannot run firefox in root as a regular user problem. 

Some guidance on this issue would be appreciated.

**Comment by jhwangbo** [comment]
Hi Ted, can you post this in raisimGym repo? This repo is only for tutorials. Thx
